# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcs',
            name='goods_size',
            field=models.CharField(choices=[('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('均码', '均码')], max_length=10, verbose_name='尺码'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='gender',
            field=models.CharField(choices=[('male', '男的'), ('female', '女的'), ('neutral', '男女同款')], default='female', max_length=10, verbose_name='性别'),
        ),
    ]
