# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20171026_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='链接'),
        ),
    ]
