# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20171026_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='singer_mobile',
            new_name='signer_mobile',
        ),
    ]
